# Redirects for Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build configuration
[build]
  command = "vite build"    # Vite's build command
  publish = "dist"          # Vite's default output directory

# Optional: Build environment variables
[build.environment]
  NODE_VERSION = "18"       # Specify Node.js version compatible with Vite
  GENERATE_SOURCEMAP = "false"
